syntax enable
set background=dark
colorscheme xoria256 
set undolevels=100
set nocompatible
set autoindent
set smartindent
set cindent
set smarttab
set expandtab
set number
set shiftwidth=4
set tabstop=4
set novisualbell 
set ruler
set guifont=Inconsolata:h12
